### ISSUE TITLE
Allow run_tests to be called more than once

### ISSUE THREAD

**Issue by ghost** [dagolden/Test-Roo#1]
Test::Routine allow calling run_tests more than once, e.g. with different arguments.

Do this for Test::Roo?  Make Test::Roo also be a Moo::Role and let run_tests compose everything into an anonymous class with create_class_with_roles?

```
for my $args ( @cases ) {
    run_tests( { roles => \@roles, desc => $desc, args =>  $args, done => 0 } );
}
```

Not sure how I'd apply a description given the current setup, but it's conceptually do-able.

**Comment by dagolden** [comment]
Alternatively, just set up Test::Roo class in a package, and let tests call it without `run_tests`.

```
package MyTest;
use Test::Roo;
# define tests
with @roles; #compose here

package main;
for my $args ( @cases ) {
    my $obj = MyTest->new($args);
    $obj->run_me;
}
done_testing;
```

This is a bit cleaner and makes composition errors easier to interpret.  Only requires refactoring the setup/do_it/teardown stuff into a method, I think.

**Comment by dagolden** [comment]
Added in 0.002
